name: Check
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Install deps
#         run: npm ci
#       - name: Lint
#         run: npm run lint

#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Install deps
#         run: npm ci
#       - name: Test
#         run: npm run test:auth
